MODULES_DB = "assets/database/modules.csv"
RSP_SCHEME_DB = "assets/database/rsp-scheme.csv"
RTL_SCHEME_DB = "assets/database/rtl-scheme.csv"
ENT_SCHEME_DB = "assets/database/ent-scheme.csv"
RSP_SALES_DB = "assets/database/rsp-sales.csv"
RTL_SALES_DB = "assets/database/rtl-sales.csv"
ENT_SALES_DB = "assets/database/ent-sales.csv"

INDEX_CSS = "assets/styles/index.css"
HOME_CSS = "assets/styles/home.css"
MODULES_CSS = "assets/styles/modules.css"