[env]
TITLE = "Online Commission Calculator"
LOGO = ":coin:"
LAYOUT = "wide"
SIDEBAR_STATE = "collapsed"

[paths]
RSALES_DB = "assests/database/retail-sales.csv"
ESALES_DB = "assets/database/enterprise-sales.csv"
MODULES_DB = "assets/database/modules.csv"
RSCHEMA_DB = "assets/database/retail-schema.csv"
ESCHEMA_DB = "assets/database/enterprise-schema.csv"
INDEX_CSS = "assets/styles/index.css"
DASHBOARD_CSS = "assets/styles/dashboard.css"
MODULES_CSS = "assets/styles/modules.css"