[env]
TITLE = "Online Commission Calculator"
LOGO = ":coin:"
LAYOUT = "wide"
SIDEBAR_STATE = "collapsed"

[paths]
RSALES_DB = "assests/database/retail-sales.csv"
ESALES_DB = "assets/database/enterprise-sales.csv"
MODULES_DB = "assets/database/modules.csv"
RSP_SCHEMA_DB = "assets/database/retail-sp-schema.csv"
RTL_SCHEMA_DB = "assets/database/retail-tl-schema.csv"
ESCHEMA_DB = "assets/database/enterprise-schema.csv"
INDEX_CSS = "assets/styles/index.css"
HOME_CSS = "assets/styles/home.css"
MODULES_CSS = "assets/styles/modules.css"