[env]
TITLE = "Online Commission Calculator"
LOGO = ":coin:"
LAYOUT = "wide"
SIDEBAR_STATE = "collapsed"

[paths]
MODULES_DB = "assets/database/modules.csv"
INDEX_CSS = "assets/styles/index.css"
DASHBOARD_CSS = "assets/styles/dashboard.css"
MODULES_CSS = "assets/styles/modules.css"